### ISSUE TITLE
Missing software licence

### ISSUE THREAD

**Issue by sommermarcel** [xmssp/PCG-OpenDRIVE#3]
Hey xmssp, 

thanks for providing the source code of this great tool. I wonder which software licence applies to your source code as there is no licence mentioned in your repository. Also it seems that GitHub does not have a default software license in case the repository itself does not provide one. Please give a short feedback if your source code can be used open source without any restrictions.

Kind regards, Marcel

**Comment by ulrichhofer** [comment]
Hi,
I am also interested in the license of this project. Without a license specification regular copyright laws apply, thus preventing others to use or extend this project in their own projects. Could you please add a license to this project or give some information, if it is possible to include this tool in other projects?

Thanks and kind regards,
Ulrich

**Comment by xmssp** [comment]
LICENSE added.
